admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin.product.add:
    path:     /add/
    defaults: { _controller: AdminBundle:Product:add}

admin.product.edit:
    path:     /product/{id}/edit
    defaults: { _controller: AdminBundle:Product:edit}
    requirements:
        id: \d+

admin.product_delete:
    path:   /product/{id}/delete
    defaults: { _controller: AdminBundle:Product:delete }
    requirements:
        id: \d+

admin.product.categorylist:
    path:     /categorylist/
    defaults: { _controller: AdminBundle:Product:categorylist }

admin.product.listbycategory:
    path:     /listbycategory/{id_category}/
    defaults: { _controller: AdminBundle:Product:listbycategory}
    requirements:
            id_category: \d+

admin.product.list:
    path:     /productlist/
    defaults: { _controller: AdminBundle:Product:productlist }

admin.product_photo_add:
    path:   /product/{idProduct}/photo/add
    defaults: { _controller: AdminBundle:ProductPhoto:add }
    requirements:
        idProduct: \d+

admin.product_photo_edit:
    path:   /product/{idPhoto}/photo/edit
    defaults: { _controller: AdminBundle:ProductPhoto:edit }
    requirements:
        idProduct: \d+

admin.product_photo_list:
    path:   /product/{idProduct}/photos
    defaults: { _controller: AdminBundle:ProductPhoto:list }
    requirements:
        idProduct: \d+

admin.category.list:
    path:   /category/list
    defaults: { _controller: AdminBundle:Category:categorylist}

admin.category.edit:
    path:   /category/{category_id}/edit
    defaults: { _controller: AdminBundle:Category:edit}
    requirements:
        category_id: \d+

admin.category.add:
    path:   /category/add
    defaults: { _controller: AdminBundle:Category:add}

admin.category.delete:
    path:   /category/{category_id}/delete
    defaults: { _controller: AdminBundle:Category:delete}
    requirements:
        category_id: \d+
