services:
    admin.img_utility:
        class: AdminBundle\Services\Image\ImageUtility
        arguments:
            - "%upload_image_type_list%"
            - "%main_product_photo_height%"
            - "%main_product_photo_width%"
            - "%image_upload_dir%"
    admin.cat_utility:
        class: AdminBundle\Services\Category\CategoryUtility
        arguments:
            - "@doctrine.orm.entity_manager"
    admin.actions_mailer:
        class: AdminBundle\Services\Mailer\MailerUtility
        arguments:
            - "%mailer_user%"
            - "%mailer_password%"
            - "@mailer"
    admin.data_loader:
        class: AdminBundle\Services\DataLoad\DataLoad
        arguments:
            - "@doctrine.orm.entity_manager"

    myshop_admin.product_subscriber:
        class: AdminBundle\Event\ProductSubscriber
        tags:
             - { name: kernel.event_listener, event: product_add_event, method: onProductAddEvent }
             - { name: kernel.event_listener, event: product_edit_event, method: onProductEditEvent }

    admin.productUtils:
        class: AdminBundle\Services\Product\ProductUtils
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"