services:
    admin.img_utility:
        class: AdminBundle\Services\Image\ImageUtility
        arguments:
            - "%upload_image_type_list%"
            - "%main_product_photo_height%"
            - "%main_product_photo_width%"
    admin.cat_utility:
            class: AdminBundle\Services\Category\CategoryUtility