services:
    my_shop.customer.handler.auth:
        class: MyShopBundle\Services\CustomerAuthHandler
        arguments:
               - "@doctrine.orm.entity_manager"
               - "@validator"
               - "@security.password_encoder"
               - "@mailer"
    my_shop.customer.handler.actions:
        class: MyShopBundle\Services\CustomerActionsHandler
        arguments:
              - "@doctrine.orm.entity_manager"