services:
    my_shop.customer.handler.auth:
        class: MyShopBundle\Services\CustomerAuthHandler
        arguments:
               - "@doctrine.orm.entity_manager"
               - "@validator"
               - "@security.password_encoder"
