<?php

namespace MyShopBundle\Repository;

/**
 * OrderProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
